string SERV_SEARCH = search
string SERV_GOHOME = goHome

string TOPIC_TURTLESTATE = turtle_states
string TOPIC_TURTLEREQUEST = turtle_request
string TOPIC_TURTLERESPONSE = turtle_response

string TOPIC_DRONESTATE = drone_states
string TOPIC_DRONEREQUEST = drone_request
string TOPIC_DRONERESPONSE = drone_response

string NODE_TURTLEHUB = turtle_hub

string STATE_STATIONARY = Stationary
string STATE_MOVING = Moving
string STATE_DOCKED = Docked
string STATE_FLYING = Flying
string STATE_LANDING = Landing